In [2]:
import numpy as np
import pandas as pd

In [3]:
appearances=pd.read_excel(r'D:\NIIT\Capstone\ds_c8_datafiles-main\appearances.xlsx')
appearances.head()

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,90
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,90
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,90
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,74
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,3

In [4]:
game_events=pd.read_excel(r'D:\NIIT\Capstone\ds_c8_datafiles-main\game_events.xlsx')
game_events.head()

,game_event_id,date,game_id,minute,type,player_id,description,player_in_id,player_assist_id
0,c6a3c088ed8a38d4ce074dd73b20d3da,2012-08-19,2221641,62,Substitutions,1335,", Not reported",45668.0,NaN
1,02d605a5c2dc4f9a6721daa583fa5405,2012-08-26,2222536,54,Cards,1321,"1. Yellow card , Foul",NaN,NaN
2,b56c2e2e087cddb3cfe9e3d340975df9,2012-11-18,2222707,79,Substitutions,104203,", Tactical",25740.0,NaN
3,4a15d1fff4f476f48bb60092c61641d5,2012-11-23,2222721,72,Substitutions,104203,", Tactical",15583.0,NaN
4,daa97877f7edf2fda885b411d7197921,2013-05-17,2222782,63,Goals,104203,", Right-footed shot, 1. Goal of the Season Ass...",NaN,15077.0

In [5]:
game_lineups=pd.read_excel(r'D:\NIIT\Capstone\ds_c8_datafiles-main\game_lineups.xlsx')
game_lineups.head()

,game_lineups_id,game_id,type,number,player_id1,player_name,team_captain,position
0,f2570d1504fc02f4b6c7608e8dcf89a3,4087925,substitutes,34,242284,Ethan Horvath,0,Goalkeeper
1,f5f0da93ea8e1d8bdd799658e7c8f7cb,4087928,starting_lineup,13,145466,Tim Ream,0,Centre-Back
2,31a4d12ec23d604779d909d26c1b5410,4087929,substitutes,26,578539,Chris Richards,0,Centre-Back
3,776dcbef98651450db76723cb7e3b4df,4087935,substitutes,26,578539,Chris Richards,0,Centre-Back
4,6a35ef7495303f29e7f85dbd54547fb1,4087936,starting_lineup,13,145466,Tim Ream,1,Centre-Back

In [6]:
games=pd.read_excel(r'D:\NIIT\Capstone\ds_c8_datafiles-main\games.xlsx')
games.head()

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,Slavoljub Muslin,Olimp-2,5700.0,Sergey Kuznetsov,NaN,NaN,FK Rostov,FK Krasnodar,02:03:00,domestic_league
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,Lars Sondergaard,Blue Water Arena,5345.0,Michael Svendsen,NaN,NaN,Esbjerg fB,Sonderjyske Fc,01:02:00,domestic_league
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,Lars Sondergaard,Cepheus Park Randers,3481.0,Jakob Kehlet,NaN,NaN,Randers Fodbold Club,Sonderjyske Fc,02:00:00,domestic_league
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,Auri Skarbalius,Ceres Park,7967.0,Kenn Hansen,NaN,NaN,Aarhus Gymnastik Forening,BRA NDBYERNES,00:03:00,domestic_league
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,NaN,NaN,Brondby IF,Odense Boldklub,00:01:00,domestic_league

In [7]:
players=pd.read_excel(r'D:\NIIT\Capstone\ds_c8_datafiles-main\players.xlsx')
players.head()

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2000000.0,15000000.0,2024-06-30,ROGON
1,223047,Emerson Hyndman,2018,903,emerson-hyndman,United States,1996-04-09,Central Midfield,Midfield,right,170.0,800000.0,1800000.0,NaT,OmniSports
2,307781,Lynden Gooch,2016,289,lynden-gooch,United States,1995-12-24,Right Winger,Attack,right,173.0,1000000.0,1000000.0,2024-06-30,Unique Sports Group
3,370846,Timothy Weah,2023,506,timothy-weah,United States,2000-02-22,Right Midfield,Midfield,right,183.0,14000000.0,15000000.0,2028-06-30,BS Group - BS Law
4,484756,Djordje Mihailovic,2023,1090,djordje-mihailovic,United States,1998-11-10,Attacking Midfield,Midfield,NaN,178.0,5000000.0,6000000.0,2026-06-30,YMU Management Ltd.

In [8]:
football=appearances.merge(game_events,on='game_id',how='outer')
football=football.merge(game_lineups,on='game_id',how='outer')
football=football.merge(games,on='game_id',how='outer')
football=football.merge(players,on='player_id_x',how='outer')

In [8]:
football.shape

(4746, 59)

In [9]:
null_counts=football.isnull().sum()
print("Null_value_counts:\n",null_counts)

Null_value_counts:
 appearance_id                   937
game_id                          60
player_id_x                     877
date_x                          937
player_name_x                   937
competition_id_x                937
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
game_event_id                  2662
date_y                         2662
minute                         2662
type_x                         2662
player_id_y                    2662
description                    3677
player_in_id                   3454
player_assist_id               4579
game_lineups_id                4502
type_y                         4502
number                         4502
player_id1                     4502
player_name_y                  4502
team_captain                   4502
position_x                     4502
competition_id_y                937
season                          937
round                           937
date                            937
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name          943
away_club_manager_name          943
stadium                         937
attendance                     1078
referee                         942
home_club_formation            4746
away_club_formation            4746
home_club_name                 1065
away_club_name                 1005
aggregate                       937
competition_type                937
name                            877
last_season                     877
current_club_id                 877
player_code                     877
country_of_birth                877
date_of_birth                   877
sub_position                    877
position_y                      877
foot                            978
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date       2314
agent_name                     1998
dtype: int64

In [10]:
football.dtypes

appearance_id                          object
game_id                               float64
player_id_x                           float64
date_x                         datetime64[ns]
player_name_x                          object
competition_id_x                       object
yellow_cards                          float64
red_cards                             float64
goals                                 float64
assists                               float64
minutes_played                        float64
game_event_id                          object
date_y                         datetime64[ns]
minute                                float64
type_x                                 object
player_id_y                           float64
description                            object
player_in_id                          float64
player_assist_id                      float64
game_lineups_id                        object
type_y                                 object
number                                float64
player_id1                            float64
player_name_y                          object
team_captain                          float64
position_x                             object
competition_id_y                       object
season                                float64
round                                  object
date                           datetime64[ns]
home_club_goals                       float64
away_club_goals                       float64
home_club_position                    float64
away_club_position                    float64
home_club_manager_name                 object
away_club_manager_name                 object
stadium                                object
attendance                            float64
referee                                object
home_club_formation                   float64
away_club_formation                   float64
home_club_name                         object
away_club_name                         object
aggregate                              object
competition_type                       object
name                                   object
last_season                           float64
current_club_id                       float64
player_code                            object
country_of_birth                       object
date_of_birth                  datetime64[ns]
sub_position                           object
position_y                             object
foot                                   object
height_in_cm                          float64
market_value_in_eur                   float64
highest_market_value_in_eur           float64
contract_expiration_date       datetime64[ns]
agent_name                             object
dtype: object

In [10]:
for column in football.columns:
    if football[column].dtype in ['int64','float64']:
        mean_value=football[column].mean()
        football[column].fillna(mean_value,inplace=True)
    elif football[column].dtype in ['object','datetime64[ns]']:
        mode_value=football[column].mode()[0]
        football[column].fillna(mode_value,inplace=True)
football

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2224728_119169,2.224728e+06,119169.0,2012-07-13,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
1,2232104_119169,2.232104e+06,119169.0,2012-07-19,Aron Johannsson,ELQ,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
2,2224568_119169,2.224568e+06,119169.0,2012-07-23,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
3,2244352_119169,2.244352e+06,119169.0,2012-07-26,Aron Johannsson,ELQ,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
4,2224567_119169,2.224567e+06,119169.0,2012-07-29,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2224542_119169,2.874689e+06,605144.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2001-07-28,Attacking Midfield,Midfield,both,180.0,2000000.0,6000000.0,2024-12-31,Octagon
4742,2224542_119169,2.874689e+06,623872.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2003-02-21,Attacking Midfield,Midfield,right,183.0,75000.0,75000.0,2024-06-30,PRO FC
4743,2224542_119169,2.874689e+06,467437.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,Germany,2002-05-28,Attacking Midfield,Midfield,right,187.0,5000000.0,5000000.0,2024-06-30,ROOF
4744,2224542_119169,2.874689e+06,103559.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,Norway,1990-10-02,Central Midfield,Midfield,right,184.0,400000.0,1400000.0,2024-05-31,Wasserman
4745,2224542_119169,2.874689e+06,670096.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2001-09-24,Central Midfield,Midfield,right,188.0,2000000.0,2500000.0,2025-06-30,PROSPORT Management

In [11]:
football.isnull().sum()

appearance_id                     0
game_id                           0
player_id_x                       0
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
game_event_id                     0
date_y                            0
minute                            0
type_x                            0
player_id_y                       0
description                       0
player_in_id                      0
player_assist_id                  0
game_lineups_id                   0
type_y                            0
number                            0
player_id1                        0
player_name_y                     0
team_captain                      0
position_x                        0
competition_id_y                  0
season                            0
round                             0
date                              0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                        0
referee                           0
home_club_formation            4746
away_club_formation            4746
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_y                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
dtype: int64

In [12]:
football.drop(['home_club_formation', 'away_club_formation'],axis=1,inplace=True)

In [13]:
football.isnull().sum()

appearance_id                  0
game_id                        0
player_id_x                    0
date_x                         0
player_name_x                  0
competition_id_x               0
yellow_cards                   0
red_cards                      0
goals                          0
assists                        0
minutes_played                 0
game_event_id                  0
date_y                         0
minute                         0
type_x                         0
player_id_y                    0
description                    0
player_in_id                   0
player_assist_id               0
game_lineups_id                0
type_y                         0
number                         0
player_id1                     0
player_name_y                  0
team_captain                   0
position_x                     0
competition_id_y               0
season                         0
round                          0
date                           0
home_club_goals                0
away_club_goals                0
home_club_position             0
away_club_position             0
home_club_manager_name         0
away_club_manager_name         0
stadium                        0
attendance                     0
referee                        0
home_club_name                 0
away_club_name                 0
aggregate                      0
competition_type               0
name                           0
last_season                    0
current_club_id                0
player_code                    0
country_of_birth               0
date_of_birth                  0
sub_position                   0
position_y                     0
foot                           0
height_in_cm                   0
market_value_in_eur            0
highest_market_value_in_eur    0
contract_expiration_date       0
agent_name                     0
dtype: int64

In [17]:
football.to_csv("D:\\NIIT\\Capstone\\Capstone\\foot_ball.csv",index=False)

In [18]:
football.to_excel("D:\\NIIT\\Capstone\\Capstone\\foot_ball.xlsx",index=False)

In [14]:
football

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2224728_119169,2.224728e+06,119169.0,2012-07-13,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
1,2232104_119169,2.232104e+06,119169.0,2012-07-19,Aron Johannsson,ELQ,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
2,2224568_119169,2.224568e+06,119169.0,2012-07-23,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
3,2244352_119169,2.244352e+06,119169.0,2012-07-26,Aron Johannsson,ELQ,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
4,2224567_119169,2.224567e+06,119169.0,2012-07-29,Aron Johannsson,DK1,0.000000,0.00000,0.000000,0.000000,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31,CAA Stellar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2224542_119169,2.874689e+06,605144.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2001-07-28,Attacking Midfield,Midfield,both,180.0,2000000.0,6000000.0,2024-12-31,Octagon
4742,2224542_119169,2.874689e+06,623872.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2003-02-21,Attacking Midfield,Midfield,right,183.0,75000.0,75000.0,2024-06-30,PRO FC
4743,2224542_119169,2.874689e+06,467437.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,Germany,2002-05-28,Attacking Midfield,Midfield,right,187.0,5000000.0,5000000.0,2024-06-30,ROOF
4744,2224542_119169,2.874689e+06,103559.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,Norway,1990-10-02,Central Midfield,Midfield,right,184.0,400000.0,1400000.0,2024-05-31,Wasserman
4745,2224542_119169,2.874689e+06,670096.0,2012-11-03,Fabian Johnson,L1,0.135994,0.00315,0.148333,0.075873,...,United States,2001-09-24,Central Midfield,Midfield,right,188.0,2000000.0,2500000.0,2025-06-30,PROSPORT Management

In [15]:
football.shape

(4746, 57)